/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#2d3449",
        "surface-container-low": "#131b2e",
        "tertiary-fixed": "#7df4ff",
        "surface-dim": "#0b1326",
        "outline-variant": "#4c4354",
        "error": "#ffb4ab",
        "on-surface-variant": "#cfc2d7",
        "on-primary-fixed": "#2c0051",
        "secondary": "#d7ffc5",
        "surface": "#0b1326",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#283044",
        "surface-container-lowest": "#060e20",
        "tertiary-container": "#006f76",
        "primary": "#dcb8ff",
        "surface-container": "#171f33",
        "on-primary-fixed-variant": "#6700b5",
        "surface-container-highest": "#2d3449",
        "on-secondary-fixed": "#022100",
        "on-primary": "#480081",
        "tertiary": "#00dbe9",
        "on-tertiary": "#00363a",
        "inverse-surface": "#dae2fd",
        "surface-bright": "#31394d",
        "on-secondary-fixed-variant": "#095300",
        "background": "#0b1326",
        "primary-fixed": "#efdbff",
        "error-container": "#93000a",
        "primary-container": "#8a2be2",
        "on-secondary-container": "#0f6d00",
        "on-tertiary-fixed-variant": "#004f54",
        "secondary-container": "#2ff801",
        "on-tertiary-fixed": "#002022",
        "secondary-fixed": "#79ff5b",
        "on-secondary": "#053900",
        "on-surface": "#dae2fd",
        "on-tertiary-container": "#75f4ff",
        "on-background": "#dae2fd",
        "surface-container-high": "#222a3d",
        "tertiary-fixed-dim": "#00dbe9",
        "surface-tint": "#dcb8ff",
        "outline": "#988ca0",
        "secondary-fixed-dim": "#2ae500",
        "primary-fixed-dim": "#dcb8ff",
        "inverse-primary": "#8422dc",
        "on-primary-container": "#eed9ff"
      },
      spacing: {
        "section-gap": "48px",
        "card-padding": "20px",
        "container-margin": "24px",
        "unit": "8px",
        "gutter": "16px"
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        heading: ["var(--font-heading)"],
      },
    },
  },
  plugins: [],
}
