"""Add trigger for automatic content_tsv population

Revision ID: d8f4e2c1b6a9
Revises: cd30829874cb
Create Date: 2026-10-08 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d8f4e2c1b6a9"
down_revision: Union[str, Sequence[str], None] = "cd30829874cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the trigger function
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_document_chunks_content_tsv()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.content_tsv := to_tsvector('english', COALESCE(NEW.content, ''));
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # Create the trigger
    op.execute(
        """
        DROP TRIGGER IF EXISTS document_chunks_content_tsv_trigger ON document_chunks;
        CREATE TRIGGER document_chunks_content_tsv_trigger
            BEFORE INSERT OR UPDATE OF content
            ON document_chunks
            FOR EACH ROW
            EXECUTE FUNCTION update_document_chunks_content_tsv();
        """
    )

    # Backfill existing rows
    op.execute(
        """
        UPDATE document_chunks
        SET content_tsv = to_tsvector('english', content)
        WHERE content_tsv IS NULL;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the trigger
    op.execute(
        """
        DROP TRIGGER IF EXISTS document_chunks_content_tsv_trigger ON document_chunks;
        """
    )

    # Drop the trigger function
    op.execute(
        """
        DROP FUNCTION IF EXISTS update_document_chunks_content_tsv();
        """
    )
    # ### end Alembic commands ###
